### ISSUE TITLE
examples?

### ISSUE THREAD

**Issue by ghost** [fewensa/rtdlib#5]
if i understand correctly this crate can be used without tdlib installed on the system. would be cool if you would provide some examples of using it

**Comment by fewensa** [comment]
Hi, I think you misunderstood, the rtdlib must need tdlib installed. if not have this, rtdlib can be work, but only create tdlib object. can not call telegram client api.

**Comment by ghost** [comment]
ah. okay, sorry for the bother

**Comment by fewensa** [comment]
Now you want call telegram client api, the rtdlib dependence https://crates.io/crates/rtdlib-sys crate.

```toml
[dependencies]
rtdlib = { version = "1.6.*", features = "sys" }
```

and this link iscreate tdlib client code

https://github.com/fewensa/telegram-client/blob/master/src/client.rs
