### ISSUE TITLE
New release and ChatMember

### ISSUE THREAD

**Issue by toxicafunk** [fewensa/rtdlib#6]
Hi,

As you know, `ChatMember`changed from having a user_id to a member_id object. I see the change already on `master` so when can we expect a new release with this change?

Thanks for this awesome library!

**Comment by fewensa** [comment]
When td release a new version https://github.com/tdlib/td/releases I'll publish a new version same with this. currently you can use 0.7.x, this version is published by master branch
https://crates.io/crates/rtdlib/0.7.1

**Comment by fewensa** [comment]
At present, the master branch will be mainly maintained, for specific reasons, please refer to  https://github.com/fewensa/telegram-client/issues/29
So, if you have any questions, you can tell me.
